Default - Local:
    model_name: /Users/samuelarnesen/nyu/llama.cpp/models/Llama-2-7b-chat-hf/
    training_hyperparameters:
        num_train_epochs: 1
        per_device_train_batch_size: 8
        gradient_accumulation_steps: 2
        optim: paged_adamw_32bit
        learning_rate: 2e-4
        max_grad_norm: 0.3
        warmup_ratio: 0.03
        lr_scheduler_type: constant
    logging_and_saving_config:
        logging_steps: 10
        output_dir: /Users/samuelarnesen/debate-data/trained_models
    prompt_config:
        prompts_file_path: ./agents/prompts/prompts.yaml
        prompt_name: Base Prompt
Default - HPC:
    model_name: /vast/spa9663/models/base_models/Llama-2-7b-chat-hf/
    training_hyperparameters:
        num_train_epochs: 1
        per_device_train_batch_size: 8
        gradient_accumulation_steps: 2
        optim: paged_adamw_32bit
        learning_rate: 2e-4
        max_grad_norm: 0.3
        warmup_ratio: 0.03
        lr_scheduler_type: constant
    logging_and_saving_config:
        logging_steps: 10
        output_dir: /vast/spa9663/models/trained_models/Llama-2-7b-chat-hf/
    prompt_config:
        prompts_file_path: /home/spa9663/debate/agents/prompts/prompts.yaml
        prompt_name: Base Prompt