13B - Alpaca - Basic:
    model_name: /vast/spa9663/models/trained_models/Llama-2-13B-32K-Merged/
    target: debater
    training_hyperparameters:
        num_train_epochs: 2
        per_device_train_batch_size: 1
        gradient_accumulation_steps: 1
        optim: paged_adamw_32bit
        learning_rate: 2e-4
        max_grad_norm: 0.3
        warmup_ratio: 0.03
        lr_scheduler_type: constant
    logging_and_saving_config:
        logging_steps: 10
        output_dir: /vast/spa9663/models/trained_models/Llama-2-13B-32K-dpo/
    prompt_config:
        prompts_file_path: /home/spa9663/debate/agents/prompts/prompts.yaml
        prompt_name: Base Prompt
13B - Alpaca - Updated:
    model_name: /vast/spa9663/models/trained_models/Llama-2-13B-32K-dpo-current/
    target: debater
    training_hyperparameters:
        num_train_epochs: 1
        per_device_train_batch_size: 1
        gradient_accumulation_steps: 1
        optim: paged_adamw_32bit
        learning_rate: 2e-4
        max_grad_norm: 0.3
        warmup_ratio: 0.03
        lr_scheduler_type: constant
    logging_and_saving_config:
        logging_steps: 10
        output_dir: /vast/spa9663/models/trained_models/Llama-2-13B-32K-dpo-4/
    prompt_config:
        prompts_file_path: /home/spa9663/debate/agents/prompts/prompts.yaml
        prompt_name: Base Prompt