Pretrain - 13B - Local:
    model_name: meta-llama/Llama-2-13b-hf
    training_hyperparameters:
        num_train_epochs: 2
        per_device_train_batch_size: 4
        gradient_accumulation_steps: 4
        optim: paged_adamw_32bit
        learning_rate: 2e-4
        max_grad_norm: 0.3
        warmup_ratio: 0.03
        lr_scheduler_type: constant
        peft_type: lora
    logging_and_saving_config:
        logging_steps: 10
        output_dir: /Users/samarnesen/nyu/scratch/not/a/real/folder
        merge_output_dir: /Users/samarnesen/nyu/scratch/not/a/real/folder
    prompt_config:
        prompts_file_path: /Users/samarnesen/nyu/debate/nyu-debate-modeling/prompts/configs/prompts.yaml
        prompt_name: Base Prompt
    dataset:
        dataset_type: quality
        train_file_path: /Users/samarnesen/nyu/debate-data/quality/data/v1.0.1/QuALITY.v1.0.1.htmlstripped.train
        val_file_path: /Users/samarnesen/nyu/debate-data/quality/data/v1.0.1/QuALITY.v1.0.1.htmlstripped.dev
        test_file_path: /Users/samarnesen/nyu/debate-data/quality/data/v1.0.1/QuALITY.v1.0.1.htmlstripped.test
        split_type: train
Pretrain - 13B:
    model_name: meta-llama/Llama-2-13b-hf
    requires_token: True
    training_hyperparameters:
        num_train_epochs: 4
        per_device_train_batch_size: 4
        gradient_accumulation_steps: 4
        optim: paged_adamw_32bit
        learning_rate: 2e-4
        max_grad_norm: 0.3
        warmup_ratio: 0.03
        lr_scheduler_type: constant
        peft_type: lora
    logging_and_saving_config:
        logging_steps: 10
        output_dir: /vast/spa9663/models/trained_models/Llama-2-Memorized/
        merge_output_dir: /vast/spa9663/models/trained_models/Llama-2-Memorized/
    prompt_config:
        prompts_file_path: /home/spa9663/debate/prompts/configs/prompts.yaml
        prompt_name: Base Prompt
    dataset:
        dataset_type: quality
        train_file_path: /home/spa9663/debate-data/quality/QuALITY.v1.0.1.htmlstripped.train
        val_file_path: /home/spa9663/debate-data/quality/QuALITY.v1.0.1.htmlstripped.dev
        test_file_path: /home/spa9663/debate-data/quality/QuALITY.v1.0.1.htmlstripped.test
        split_type: train