Basic:
    model_name: ""
    training_hyperparameters:
        num_train_epochs: 25
        per_device_train_batch_size: 16
        learning_rate: 10e-5
        supplemental:
            hidden_size: 4096
            linear_idxs:
                - -1
    logging_and_saving_config:
        logging_steps: 10
        output_dir: /vast/spa9663/models/trained_models/mixtral-linear-probe-small
    dataset:
        dataset_type: judging_probe
        combine_train_and_val: True
        full_dataset_file_path: 
            - /vast/spa9663/outputs/transcripts/2024-01-27_22:52:19.226386
            - /vast/spa9663/outputs/transcripts/2024-01-30_01:17:56.251526