services:
  backend:
    build:
      context: ..
      dockerfile: explorer/explorer_backend/Dockerfile
    environment:
      INPUT_ROOT: /app/data/
      SRC_ROOT: /app/
      PYTHONPATH: /app
    ports:
      - "8067:8067"
    volumes:
      - ${HOME}/.ssh/lambda-labs.pem:/root/.ssh/lambda-labs.pem:ro

  frontend:
    build:
      context: ./explorer-frontend
      dockerfile: Dockerfile
      args:
        VITE_EXPLORER_API_BASE: http://localhost:8067
    depends_on:
      - backend
    ports:
      - "5173:80"
