configurations:
  - instance_ip: 192.222.51.244
    home_dir: /home/ubuntu/mars-arnesen-gh/garethtan
    configurations:
      name: debater-trained-judge-trained
      num_iters: 150
      count: 4
  - instance_ip: 192.222.58.228
    home_dir: /home/ubuntu/mars-arnesen-gh/garethtan
    configurations:
      name: debater-untrained-judge-trained
      num_iters: 100
      count: 2
