configurations:
  - instance_ip: 150.136.69.141
    configurations:
      name: debater-trained-judge-untrained
      num_iters: 100
      count: 2
  - instance_ip: 192.222.50.9
    configurations:
      name: debater-trained-judge-untrained
      num_iters: 100
      count: 4
